# Generation settings default values
TEMPERATURE_UPDATE_METHOD_IDENTIFIER = 'c'
INITIAL_TEMPERATURE = 100
COOLING_RATE = 0.9
FINAL_TEMPERATURE = 10
NUMBER_OF_ITERATIONS = 1000


# Generation limitations
VALUE_RESOLUTION = 2

MIN_R_VALUE = 5
MIN_GREEN_LIGHT_LENGTH = 5

MIN_P_VALUE = 0
MAX_P_VALUE = 20

MIN_T_VALUE = MIN_GREEN_LIGHT_LENGTH + MIN_R_VALUE
MAX_T_VALUE = 20
