
# Generation limitations
DECIMAL_PLACES = 2
MIN_R_VALUE = 10
MIN_GREEN_LIGHT_LENGTH = 10
MIN_T_VALUE = MIN_GREEN_LIGHT_LENGTH + MIN_R_VALUE
MAX_T_VALUE = 30
MIN_P_VALUE = 0
MAX_P_VALUE = MAX_T_VALUE


# Generation settings default values
TEMPERATURE_UPDATE_METHOD_IDENTIFIER = 'j'
INITIAL_TEMPERATURE = 100
COOLING_RATE = 0.99
FINAL_TEMPERATURE = 1
NUMBER_OF_ITERATIONS = 10000
STARTING_TIMES = [0, 10, 5]
